#!/bin/python3

import math
import os
import random
import re
import sys

kn = []
ar = []
t = int(input())
for i in range(0,t):
    kn.append(list(map(int,input().rstrip().split())))
    ar.append(list(map(int,input().rstrip().split())))
# Complete the angryProfessor function below.
def angryProfessor(kn, ar):
    
    for i in range(0,len(ar)):
        a = ar[i]
        k = kn[i]
        n = 0
        for j in range(0,len(a)):
            if a[j]<=0:
                n=n+1
        if n>=k[1]:
            print('NO')
        else:
            print('YES')
           


angryProfessor(kn, ar)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        n = int(nk[0])

        k = int(nk[1])

        a = list(map(int, input().rstrip().split()))

        result = angryProfessor(k, a)

        fptr.write(result + '\n')

    fptr.close()
"""
