#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles,n):
    j=0
    maxi = max(candles)
    for i in range(0,n):
        if candles[i]==maxi:
            j=j+1
    return print(j)
    # Write your code here


n = int(input())
candles = list(map(int,input().rstrip().split()))
birthdayCakeCandles(candles,n)
#if __name__ == '__main__':
#    fptr = open(os.environ['OUTPUT_PATH'], 'w')

#    candles_count = int(input().strip())

 #   candles = list(map(int, input().rstrip().split()))

#    result = birthdayCakeCandles(candles)
#
 #   fptr.write(str(result) + '\n')
#
 #   fptr.close()
