#!/bin/python3

import math
import os
import random
import re
import sys

n = int(input())
scores = list(map(int,input().rstrip().split()))
# Complete the breakingRecords function below.
def breakingRecords(scores):
    highest = [-1]*len(scores)
    lowest = [pow(10,9)]*len(scores)
    lowchange = -1
    highchange = -1
    for i in range(0,len(scores)):
        if scores[i]>max(highest):
            highest[i]=scores[i]
            highchange += 1
        else:
            highest[i]=highest[i-1]
        if scores[i]<min(lowest):
            lowest[i]=scores[i]
            lowchange += 1
        else:
            lowest[i]=lowest[i-1]
        
    return print(highchange, lowchange)

    
breakingRecords(scores)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
"""
