#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#
steps = int(input())
path = str(input())
#path = list(map(str,input().rstrip().split())
def countingValleys(steps, path):
    my_dict = {'U':1,'D':-1}
    nv = 0
    count = [0]
    for i in range(0,steps):
        count.append(count[i]+my_dict[path[i]])
    for j in range(1,len(count)):
        if count[j-1]==0 and count[j]==-1:
            nv = nv+1
    return print(nv)

countingValleys(steps, path)
