#!/bin/python3

import math
import os
import random
import re
import sys
n = int(input())
arr = list(map(int,input().rstrip().split()))
# Complete the cutTheSticks function below.
def cutTheSticks(arr):
    newar = list(set(arr))
    newar.sort()
    sm = 0
    print(len(arr))
    #print(newar)
    for i in range(0,len(newar)):
        sm=sm+arr.count(newar[i])
        if len(arr)-sm!=0:
            print(len(arr)-sm)
        
    
cutTheSticks(arr)
