#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr,n):
    s1 = 0
    s2 = 0
    for i in range(0,n):
        s1 = s1 + arr[i][i]
    for i in range(1,n+1):
        s2 = s2 + arr[n-i][i-1]
    diff = abs(s1 - s2)


    return print(diff)
        
    # Write your code here


n = int(input())
arr= []
for i in range(1,n+1):
    arr.append(list(map(int,input().rstrip().split())))
    

diagonalDifference(arr,n)


