#!/bin/python3

import math
import os
import random
import re
import sys

nk =list(map(int,input().rstrip().split()))
n = nk[0]
k = nk[1]
ar = list(map(int,input().rstrip().split()))

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    ans = 0
    for i in range(0,len(ar)):
        for j in range(i+1,len(ar)):
            if (ar[i]+ar[j])%k==0:
                ans += 1
    return print(ans)

   
divisibleSumPairs(n, k, ar)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
"""
