#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    ngrades = []
    for i in range(0,len(grades)):
        if grades[i]%5==0:
            ngrades.append(grades[i])
        elif grades[i]<38:
            ngrades.append(grades[i])
        elif grades[i]%5==3 or grades[i]%5==4:
            ngrades.append(grades[i]+5-grades[i]%5)
        else:
            ngrades.append(grades[i])
    ans = str(ngrades)
    for i in range(0,len(grades)):
        print(ngrades[i])
    # Write your code here

    
n = int(input())
grades = []
for i in range(0,n):
    grades.append(int(input().strip()))

gradingStudents(grades)
"""    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
"""
