#!/bin/python3

import math
import os
import random
import re
import sys

V = int(input())
n = int(input())
arr = list(map(int,input().rstrip().split()))
# Complete the introTutorial function below.
def introTutorial(V, arr):
    for i in range(0,len(arr)):
        if arr[i]==V:
            print(i)

    
 
introTutorial(V, arr)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    V = int(input())

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = introTutorial(V, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
"""
