#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(xv):
    x1 = xv[0]
    v1 = xv[1]
    x2 = xv[2]
    v2 = xv[3]
    
    """
    if x1<x2 and v1>v2:
        print('YES')
    elif x1>x2 and v1<v2:
        print('YES')
    elif x1==x2:
        print('YES')
    else:
        print('NO')
    """
    
    if v1!=v2 and x1!=x2:
        check = (x2 - x1)/(v1 - v2)
        if check>0 and int(check)==check:
            print('YES')
        else:
            print('NO')
    elif v1==v2:
        if x1==x2:
            print('YES')
        else:
            print('NO')
    elif x1==x2:
        print('YES')
    else:
        print('NO')
            
            

xv = list(map(int, input().rstrip().split()))
kangaroo(xv)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
"""
