#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#
n = int(input())
a = list(map(int,input().rstrip().split()))
def pickingNumbers(a):
    a.sort()
    ANS = []
    for i in range(0,len(a)):
        ans = 1
        for j in range(i+1,len(a)):
            if abs(a[i]-a[j])<=1:
                ans+=1
        ANS.append(ans)
    print(max(ANS))
    # Write your code here
pickingNumbers(a)
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
"""
