#!/bin/python3

import math
import os
import random
import re
import sys

n = int(input())
p = list(map(int,input().rstrip().split()))
# Complete the permutationEquation function below.
def permutationEquation(n,p):
    for i in range(1,n+1):
        for j in range(0,n):
            if i==p[p[j]-1]:
                print(j+1)
    

    
permutationEquation(n,p)
    
"""
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
"""
