#!/bin/python3

import math
import os
import random
import re
import sys

nk = list(map(int,input().rstrip().split()))
n = nk[0]
k = nk[1]
height = list(map(int,input().rstrip().split()))
# Complete the hurdleRace function below.
def hurdleRace(k, height):
    m = max(height)
    if k>=m:
        print(0)
    else:
        print(m-k)
        

    
    
    
hurdleRace(k, height)
"""    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    height = list(map(int, input().rstrip().split()))

    result = hurdleRace(k, height)

    fptr.write(str(result) + '\n')

    fptr.close()
"""
